project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
preserve_hierarchy: false
files:
  - source: "apps/web/messages/pt-BR.json"
    translation: "apps/web/messages/%locale%.json"
